server:
  port: 8080

spring:
  application:
    name: salesapi
  datasource:
    url: jdbc:h2:mem:orderdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

management:
  endpoints.web.exposure.include: health,info,metrics,prometheus,threaddump,heapdump
  otlp.tracing.endpoint: http://otel-collector:4317
